#!/usr/bin/env python3
"""Writes the .lproj tables for Compositor from scripts/l10n/translations.py.

English is the source language, so en.lproj maps each key to itself: that is what makes the English
wording a stable lookup key for both `String(localized:)`-style calls and SwiftUI's `Text("literal")`,
and what lets a missing translation fall back to English instead of to an identifier.

Run with `--report` to list strings the sources use that have no translation yet, and translations
that no source uses. Neither is an error: coverage is meant to grow, and a stale entry is only worth
removing once it is clearly gone.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))

from translations import TRANSLATIONS  # noqa: E402


def escape(value: str) -> str:
    """Escapes a string for a .strings file: backslashes, quotes and newlines only."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_table(path: pathlib.Path, pairs) -> None:
    lines = [
        "/* Generated by scripts/l10n/build-strings.py — do not edit by hand. */",
        "",
    ]
    for key, value in pairs:
        lines.append(f'"{escape(key)}" = "{escape(value)}";')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)} ({len(pairs)} entries)")


def source_strings() -> set:
    """Every literal a lookup could use, so coverage can be reported honestly."""
    pattern = re.compile(r'"((?:[^"\\]|\\.)*)"')
    found = set()
    for path in sorted((ROOT / "Compositor").rglob("*.swift")):
        if path.name == "Localization.swift":
            continue
        for match in pattern.finditer(path.read_text(encoding="utf-8")):
            found.add(match.group(1))
    return found


def main() -> None:
    pairs = sorted(TRANSLATIONS.items())
    write_table(ROOT / "Compositor/en.lproj/Localizable.strings",
                [(key, key) for key, _ in pairs])
    write_table(ROOT / "Compositor/zh-Hans.lproj/Localizable.strings", pairs)

    if "--report" in sys.argv:
        used = source_strings()
        untranslated = sorted(s for s in used
                              if s not in TRANSLATIONS
                              and re.search(r"[A-Za-z]{2}", s)
                              and not re.match(r"^[a-z0-9_.\-/:]+$", s))
        stale = sorted(k for k in TRANSLATIONS if k not in used)
        print(f"\nuntranslated candidates in sources: {len(untranslated)}")
        for s in untranslated[:400]:
            print(f"  {s!r}")
        if stale:
            print(f"\ntranslations no source uses ({len(stale)}):")
            for s in stale:
                print(f"  {s!r}")


if __name__ == "__main__":
    main()
